### ISSUE TITLE
Cirar inputs correspondentes às informações no Backend para os formulários

### ISSUE THREAD

**Issue by DoomerO** [DoomerO/WillChair#6]
faltam inputs necessários para a criação de oferta e produto nos formulários

**Comment by DoomerO** [comment]
Os formulários estão longe de serem completos e o estilo está quebrado. Dá para mexer neles apesar disso, no entanto é um processo cansativo. Devem ser corrigidos todos exceto o Wc.

**Comment by Mylliee** [comment]
Vou dar commit nos meus dois formulário amanhã, estão quase completos. O Barbosa tem que ver os dois dele.

**Comment by DoomerO** [comment]
Os formulários finalizados, deve ser apenas feitas verificações de estilo e erros eventuais
